config/routes.rb
Rails.application.routes.draw do
  get 'prefectures/show'
  root to: 'contents#index'
  devise_for :users
  resources :contents do
    resources :posts, only: [:show, :new, :create, :destroy, :edit, :update]
    collection do
      get 'articles'
      get 'photos'
      get 'search'
    end
  end
  resources :comments, only: [:create, :destroy]
  resources :users, only: [:show]
  resources :prefectures, only: [:show]
end

app/models/content.rb
class Content < ApplicationRecord

  with_options presence: true do
    validates :title
    validates :from_date
    validates :return_date
  end
  
  belongs_to :user
  has_many :posts, dependent: :destroy

end

app/controllers/contents_controller.rb
class ContentsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show, :articles, :photos, :prefectures, :search]
  before_action :set_content, only: [:check_user, :show, :destroy, :edit, :update]
  before_action :check_user, only: [:edit, :destroy, :update]

  def index
   @contents = Content.order('created_at DESC').includes(:user)
   @contents = @contents.first(3)
   @prefectures = Prefecture.where.not(id: 1)
  end

  def new
    @content = Content.new
  end

  def create
    @content = Content.new(content_params)
    if @content.save
      redirect_to content_path(@content.id)
    else
      render :new
    end
  end

  def show
    @posts = Post.where(content_id: @content.id).order('travel_date')
  end

  def destroy
    @content.destroy
    redirect_to root_path
  end

  def edit
  end

  def update
    if @content.update(content_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  def articles
    @contents = Content.order('created_at DESC').page(params[:page]).per(5).includes(:user)
  end

  def photos
    @posts = Post.order('created_at DESC').page(params[:page]).per(4)
  end

  def search
    @posts = Post.order('travel_date DESC').search(params[:keyword]).page(params[:page]).per(15)
  end

  private
  def content_params
    params.require(:content).permit(:title, :from_date, :return_date).merge(user_id: current_user.id)
  end

  def set_content
    @content = Content.find(params[:id])
  end

  def check_user
    unless current_user.id == @content.user_id
      redirect_to content_path(@content.id)
    end
  end

end

app/views/contents/articles.html.erb
<div class="article-wrapper">
  <div class="article-container">
    <h3 id="new-articles-list">記事一覧</h3>
      <%= paginate @contents %>
      <% @contents.each do |content| %>
        <div class="article-list">
          <div class="new-article">
            <%= link_to content.title, content_path(content.id)%></br>
            <div class="article-form"><%= content.from_date %> ~ <%= content.return_date %></div></br>
            <%= link_to content.user.nickname, user_path(content.user_id) %></br>
          </div>
          <div class="new-article-photo">
            <%= image_tag content.posts[0].images[0].variant(resize: '300x203').processed, class:"image-tag" %>
          </div>
        </div>
      <% end %>
      <%= paginate @contents %>
  </div>
</div>

app/views/contents/edit.html.erb
<div class="content_new-wrapper">
  <div class="content_new-container">
    <h2>旅の記録を編集する <i class="fas fa-edit"></i></h2>
    <div class="content-form">
      <%= form_with(model: @content, local: true) do |f| %>
        <%= render 'layouts/error_messages', model: f.object %>
        <%= f.label :title,"タイトル" ,class:"content-title"%>
        <%= f.text_field :title , class:"content-form-box"%></br>
        <%= f.label :from_date,"出発日　"%>
        <%= f.date_field :from_date, class:"content-form-box" %></br>
        <%= f.label :return_date,"帰着日　"%>
        <%= f.date_field :return_date, class:"content-form-box" %></br>
        <%= f.submit "変更する" , class:"create-btn" %>
        <%= link_to "戻る",content_path(@content.id) %>
      <% end %>
    </div>
  </div>
</div>

app/views/contents/index.html.erb
<!-- index-main -->
<div class="index-wrapper">
  <div class="index-main-wrapper">
    <div class="index-main-container">
      <h1>Travel Photo21</h1>
      <h2>旅の写真を公開しよう</h2>
      <%= link_to "新しい旅を投稿する",new_content_path ,class:"index-main-link"%>
    </div>  
  </div>
  <!-- 上部メニュー部分 -->
  <div class="index-menu-bar">
    <div class="index-menu">
      <ul class="index-menu-lists">
        <li><a href="#new-articles-list">最新記事</a></li>
        <li><%= link_to "記事一覧", articles_contents_path %></li>
        <li><%= link_to "画像一覧", photos_contents_path %></li>
        <li><%= link_to "都道府県別一覧", root_path, id:"index-prefecture" %></li>
      </ul>
      <ul class="show-lists none" id="pull-down">
        <% @prefectures.each do |prefecture| %>
          <% if prefecture.present? && prefecture.posts.length != 0  %>
            <li><%= link_to "#{prefecture.name} (#{prefecture.posts.length})", prefecture_path(prefecture.id) %></li>
          <% else %>
            <li><%= prefecture.name %></li>
          <% end %>
        <% end %>
      </ul>
    </div>
  </div>
  <!-- index-bottom -->
  <div class="index-bottom-wrapper">
    <div class="index-bottom">
      <h3 id="new-articles-list">最新記事</h3>
        <% @contents.each do |content| %>
          <div class="article-list">
            <div class="new-article">
              <%= link_to content.title, content_path(content.id) %></br>
              <div class="article-form"><%= content.from_date %> ~ <%= content.return_date %></div></br>
              <%= link_to content.user.nickname, user_path(content.user_id)%></br>
            </div>
            <div class="new-article-photo">
              <% if content.posts[0].images[0].present? %>
                <%= image_tag content.posts[0].images[0].variant(resize: '300x203').processed, class:"image-tag" %>
              <% else %>
                現在、表示できるアルバムはありません
              <% end %>
            </div>
          </div>
        <% end %>
    </div>
  </div>
</div>

app/views/contents/new.html.erb
<div class="content_new-wrapper">
  <div class="content_new-container">
    <h2>新しい旅の記録を作成 <i class="fa fa-book" aria-hidden="true"></i></h2>
    <div class="content-form">
      <%= form_with(model: @content, local: true) do |f| %>
        <%= render 'layouts/error_messages', model: f.object %>
        <%= f.label :title,"タイトル" ,class:"content-title"%>
        <%= f.text_field :title ,placeholder:"例）沖縄満喫の旅", class:"content-form-box"%></br>
        <%= f.label :from_date,"出発日　"%>
        <%= f.date_field :from_date, class:"content-form-box" %></br>
        <%= f.label :return_date,"帰着日　"%>
        <%= f.date_field :return_date, class:"content-form-box" %></br>
        <%= f.submit "作成する" , class:"create-btn" %>
        <%= link_to "戻る",contents_path %>
      <% end %>
    </div>
  </div>
</div>

app/views/contents/photos.html.erb
<div class="article-wrapper">
  <div class="article-container">
    <h3 id="new-articles-list">写真一覧</h3>
    <%= paginate @posts %>
    <div class="photos-lists">
      <% @posts.each do |post| %>
        <% post.images.each do |image| %>
          <div class="photo"><%= link_to image_tag(image.variant(resize: '200x200').processed), content_post_path(post.content_id,post.id) %></div>
        <% end %>  
      <% end %>
    </div>
    <%= paginate @posts %>
  </div>
</div>

app/views/contents/search.html.erb
<div class="article-wrapper">
  <div class="content_show-container">
    <h3 id="new-articles-list"><%= "検索結果" %></h3>
      <table border="1">
        <tr><th>日付</th><th>タイトル</th></tr>
        <% @posts.each do |post| %>
          <div>
            <tr><td><%= link_to post.travel_date, content_post_path(post.content_id,post.id) %></td>
            <td><%= post.subject %></td></tr>
          </div>
        <% end %>
      </table>
      <%= paginate @posts %>
    <%= link_to "戻る",root_path, class:"content_show-link" %>
  </div>
</div>

app/views/contents/show.html.erb
<div class="content_show-wrapper">
  <div class="content_show-container">
    <h3 id="new-articles-list"><%= @content.title %></h3>
      <p>旅行期間 <i class="far fa-calendar-alt"></i>　<%= @content.from_date %> ~ <%= @content.return_date %></p></br>
      <div class="content_show-user">ユーザー：　<%= link_to @content.user.nickname, user_path(@content.user.id)%></div></br>
      <table border="1">
        <tr><th>日付</th><th>タイトル</th></tr>
        <% @posts.each do |post| %>
          <div>
            <tr><td><%= link_to post.travel_date, content_post_path(post.content_id,post.id) %></td>
            <td><%= post.subject %></td></tr>
          </div>
        <% end %>
      </table>

        <% if user_signed_in? && current_user.id == @content.user_id %>
          <%= link_to "新しいアルバムを追加", new_content_post_path(content_id: @content.id), class:"content_show-link" %>
          
          
        
          <%= link_to "編集する", edit_content_path(@content.id), class:"content_show-link" %>
          <%= link_to "削除する", content_path(@content.id), method: :delete, class:"content_show-link" %>
        <% end %>
        <%= link_to "戻る",contents_path, class:"content_show-link" %>
      </div>
  </div>
</div>