config/routes.rb
Rails.application.routes.draw do
  get 'prefectures/show'
  root to: 'contents#index'
  devise_for :users
  resources :contents do
    resources :posts, only: [:show, :new, :create, :destroy, :edit, :update]
    collection do
      get 'articles'
      get 'photos'
      get 'search'
    end
  end
  resources :comments, only: [:create, :destroy]
  resources :users, only: [:show]
  resources :prefectures, only: [:show]
end

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
  <div class="error-alert">
    <ul>
      <% model.errors.full_messages.each do |message| %>
        <li class='error-message'><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer>
  <div class="footer-container">
    <p>©️Travel Photo21</p>
  </div>
</footer>

app/views/shared/_header.html.erb
<header>
    <div class="header-bar">
      <div class="header-left">
        <%= link_to image_tag("logo.png",size: '350x60'), "/", class:"image-tag" %>
      </div>
      <div class="header-center">
        <%= form_with(url: search_contents_path, local: true, method: :get, class: "search-form") do |f| %>
        <%= f.text_field :keyword, placeholder: "　\uF002", class: "search-input" %>
        <%= f.submit "検索", class: "search-btn" %>
        <% end %>
      </div>
      <div class="header-right">
        <% if user_signed_in? %>
          <div class="header-user-container">
            <%= image_tag "arrow.png", class:"arrow" %>
            <%= link_to current_user.nickname, user_path(current_user.id), class: "header-user" %>
          </div>
          <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class:"sign-btn" %>
        <% else %>
          <%= link_to "新規会員登録", new_user_registration_path, class:"sign-btn" %>
          <%= link_to "ログイン", new_user_session_path,  class:"sign-btn" %>
        <% end %>
      </div>
    </div>
</header>