config/routes.rb
Rails.application.routes.draw do
  get 'prefectures/show'
  root to: 'contents#index'
  devise_for :users
  resources :contents do
    resources :posts, only: [:show, :new, :create, :destroy, :edit, :update]
    collection do
      get 'articles'
      get 'photos'
      get 'search'
    end
  end
  resources :comments, only: [:create, :destroy]
  resources :users, only: [:show]
  resources :prefectures, only: [:show]
end

app/models/post.rb
class Post < ApplicationRecord
  with_options presence: true do
    validates :subject
    validates :travel_date
    validates :prefecture_id, numericality:{other_than: 1,message: 'を選択してください'}
    validates :article
    validates :images
  end

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :prefecture

  belongs_to :user
  belongs_to :content
  has_many_attached :images
  has_many :comments

  def self.search(search)
    if search != ""
      Post.where('article LIKE(?) OR subject LIKE(?)', "%#{search}%","%#{search}%")
    else
      Post.order('travel_date DESC')
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, except: [:show]
  before_action :set_post, only: [:show, :destroy, :edit, :update]
  before_action :check_user, only: [:new, :create, :edit, :destroy, :update]

  def show
    @comments = Comment.where(post_id: @post.id).order("created_at DESC").includes(:user)
  end

  def new
    @post = Post.new
    @comment = Comment.new
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      redirect_to content_post_path(@post.content_id,@post.id)
    else
      render :new
    end
  end

  def destroy
    @post.destroy
    redirect_to content_path(@post.content.id)
  end

  def edit
  end

  def update
    if @post.update(post_params)
      redirect_to content_post_path(@post.content_id,@post.id)
    else
      render :edit
    end
  end

  private
  def post_params
    params.require(:post).permit(:subject, :travel_date, :prefecture_id, :article, images: [] ).merge(user_id: current_user.id, content_id: params[:content_id])
  end

  def set_post
    @post = Post.find(params[:id])
  end

  def check_user
    content = Content.find(params[:content_id])
    unless current_user.id == content.user_id
      redirect_to content_post_path(@post.content_id,@post.id)
    end
  end

end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/edit.html.erb
<div class="post_new-wrapper">
  <div class="content_new-container">
  <h2>アルバムを編集する <i class="far fa-images"></i></h2>
    <div class="content-form">
      <%= form_with(model: @post, url:content_post_path, local: true) do |f| %>
      <%= render 'layouts/error_messages', model: f.object %>
      <div class="post-form">
        <%= f.label :subject, "タイトル　　" ,class:"post-title"%>
        <%= f.text_field :subject, autofocus: true, autocomplete: "subject", class:"post-new-form" %></br>
      </div>
      <div class="post-form">
        <%= f.label :travel_date, "日付　　　　" %>
        <%= f.date_field :travel_date, autocomplete: "travel_date",class:"post-new-form" %></br>
      </div>
      <div class="post-form">
        <%= f.label :prefecture_id, "都道府県　　" %>
        <%= f.collection_select(:prefecture_id, Prefecture.all, :id, :name) %></br>
      </div>
      <div class="post-form">
        <%= f.label :article, "テキスト　　" ,class:"post-text-title"%>
        <%= f.text_area :article, autocomplete: "article", row:"6", class:"post-text"%></br>
      </div>
      <div class="post-form">
        <%= f.label :images, "画像を選択　" %><i class="far fa-images"></i>
        <%= f.file_field :images, multiple: true %></br>
      </div>
      <div class="post-submit-form">
        <%= f.submit "保存する" , class:"post-submit-btn"%>
        <%= link_to "戻る",content_post_path(@post.content_id,@post.id) %>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/posts/new.html.erb
<div class="post_new-wrapper">
  <div class="content_new-container">
  <h2>新しいアルバムを作成 <i class="far fa-images"></i></h2>
    <div class="content-form">
      <%= form_with(model: @post, url:content_posts_path, local: true) do |f| %>
      <%= render 'layouts/error_messages', model: f.object %>
      <div class="post-form">
        <%= f.label :subject, "タイトル　　" ,class:"post-title"%>
        <%= f.text_field :subject, autofocus: true, autocomplete: "subject", class:"post-new-form" %></br>
      </div>
      <div class="post-form">
        <%= f.label :travel_date, "日付　　　　" %>
        <%= f.date_field :travel_date, autocomplete: "travel_date",class:"post-new-form" %></br>
      </div>
      <div class="post-form">
        <%= f.label :prefecture_id, "都道府県　　" %>
        <%= f.collection_select(:prefecture_id, Prefecture.all, :id, :name) %></br>
      </div>
      <div class="post-form">
        <%= f.label :article, "テキスト　　" ,class:"post-text-title"%>
        <%= f.text_area :article, autocomplete: "article", row:"6", class:"post-text"%></br>
      </div>
      <div class="post-form">
        <%= f.label :images, "画像を選択　" %><i class="far fa-images"></i>
        <%= f.file_field :images, multiple: true %></br>
      </div>
      <div class="post-submit-form">
        <%= f.submit "作成する" , class:"post-submit-btn"%>
        <%= link_to "戻る",content_path(id: params[:content_id]) %>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/posts/show.html.erb
<div class="posts_show-wrapper">
  <div class="posts_show-container">
    <div class="photos-container">
      <% @post.images.each do |image| %>
        <div class="photos">
          <%= link_to image, "data-lightbox": image do %>
            <%= image_tag image.variant(resize: '400x400') %>
          <% end %>
        </div>
      <% end %>
    </div>
    <div class="text-container">
      <h2 class="post-subject"><%= @post.subject %></h2>
      <span><%= @post.travel_date %></span>
      <soan><%= @post.prefecture.name %></span></br>
      <div><%= link_to @post.user.nickname, user_path(@post.user_id)%> の投稿</div>

      <div class="posts-link">
        <% if user_signed_in? && current_user.id == @post.user_id %>
          <span><%= link_to "編集", edit_content_post_path(@post.content_id, @post.id) %></span>
          <span><%= link_to "削除", content_post_path(@post.content_id, @post.id), method: :delete%></span>
        <% end %>
        <span><%= link_to "一覧へ", content_path(@post.content_id) %></span></br> 
      </div>
      <div class="post-article"><%= @post.article %></div>
      <div class="comment-container">
      <% if user_signed_in? %>  
        <h3>コメントはこちらへ <i class="far fa-comment-dots"></i></h3>
        <div>
          <%= form_with(model: @comment, url: comments_path, local: true) do |f| %>
          <%= alert %>
          <%= f.text_field :text ,size:"24"%>
          <%= f.hidden_field :post_id, :value => @post.id %>
          <div class="comment-btn"><%= f.submit "コメントする" %></div>
          <% end %>
        </div>
      <% else %>
        <h3>** ログインしてください<i class="far fa-comment-dots"></i> **</h3></br>
      <% end %>

        <% @comments.each do |comment| %>
          <div class="comments">
            <%= l comment.created_at %>
            <%= link_to "削除する", comment_path(comment.id), method: :delete if user_signed_in? && current_user.id == comment.user_id %></br>  
            <%= link_to comment.user.nickname, user_path(comment.user_id)%></br>
            <div class="comment"><%= comment.text %></div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>